/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote.telas;

import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Formatter;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mayra.jpereira
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private TelaProdutos produtos = null;
    private TelaClientes clientes = null;
    private TelaVenda venda = null;
    private TelaRelatorio relatorio = null;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        labelRelogio.setText(sdf.format(date));
        
    }  
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBarMenu = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        bttCliente = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        bttProduto = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        bttVenda = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        bttRelatorio = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        bttSair = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        labelRelogio = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja de Instrumentos");

        toolBarMenu.setFloatable(false);
        toolBarMenu.setOrientation(javax.swing.SwingConstants.VERTICAL);
        toolBarMenu.setRollover(true);

        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        toolBarMenu.add(jSeparator1);

        bttCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/telas/usuarios.png"))); // NOI18N
        bttCliente.setText("Clientes");
        bttCliente.setFocusable(false);
        bttCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttCliente.setMaximumSize(new java.awt.Dimension(70, 90));
        bttCliente.setMinimumSize(new java.awt.Dimension(70, 90));
        bttCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttClienteActionPerformed(evt);
            }
        });
        toolBarMenu.add(bttCliente);
        toolBarMenu.add(jSeparator2);

        bttProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/telas/guitarra.png"))); // NOI18N
        bttProduto.setText("Produtos");
        bttProduto.setFocusable(false);
        bttProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttProduto.setMaximumSize(new java.awt.Dimension(70, 90));
        bttProduto.setMinimumSize(new java.awt.Dimension(70, 90));
        bttProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttProdutoActionPerformed(evt);
            }
        });
        toolBarMenu.add(bttProduto);
        toolBarMenu.add(jSeparator3);

        bttVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/telas/venda.png"))); // NOI18N
        bttVenda.setText("Venda");
        bttVenda.setFocusable(false);
        bttVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttVenda.setMaximumSize(new java.awt.Dimension(70, 90));
        bttVenda.setMinimumSize(new java.awt.Dimension(70, 90));
        bttVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVendaActionPerformed(evt);
            }
        });
        toolBarMenu.add(bttVenda);
        toolBarMenu.add(jSeparator4);

        bttRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/telas/relatorio.png"))); // NOI18N
        bttRelatorio.setText("Relatório");
        bttRelatorio.setFocusable(false);
        bttRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttRelatorio.setMaximumSize(new java.awt.Dimension(70, 90));
        bttRelatorio.setMinimumSize(new java.awt.Dimension(70, 90));
        bttRelatorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRelatorioActionPerformed(evt);
            }
        });
        toolBarMenu.add(bttRelatorio);
        toolBarMenu.add(jSeparator7);

        bttSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/telas/sair.png"))); // NOI18N
        bttSair.setText("Sair");
        bttSair.setFocusable(false);
        bttSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttSair.setMaximumSize(new java.awt.Dimension(70, 90));
        bttSair.setMinimumSize(new java.awt.Dimension(70, 90));
        bttSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSairActionPerformed(evt);
            }
        });
        toolBarMenu.add(bttSair);
        toolBarMenu.add(jSeparator5);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pacote/telas/1494277231_date.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(70, 90));
        jLabel1.setMinimumSize(new java.awt.Dimension(70, 90));
        toolBarMenu.add(jLabel1);

        labelRelogio.setText("       Data");
        labelRelogio.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labelRelogio.setMaximumSize(new java.awt.Dimension(70, 15));
        labelRelogio.setMinimumSize(new java.awt.Dimension(70, 15));
        toolBarMenu.add(labelRelogio);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void openInCenter(JInternalFrame jif){
        Dimension desktopSize = desktop.getSize();
        Dimension jInternalFrameSize = jif.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        jif.setLocation(width, height);
        jif.setVisible(true);
    }
    
    private void bttClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClienteActionPerformed
       if(this.clientes==null || !this.clientes.isDisplayable()){
            clientes = new TelaClientes();
            desktop.add(clientes);
            clientes.setVisible(true);
            this.openInCenter(clientes);
       }
       clientes.toFront();
       
    }//GEN-LAST:event_bttClienteActionPerformed

    private void bttProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttProdutoActionPerformed
        if(this.produtos==null || !this.produtos.isDisplayable()){
            produtos = new TelaProdutos();            
            desktop.add(produtos);
            produtos.setVisible(true);
            this.openInCenter(produtos);
        }
        produtos.toFront();
    }//GEN-LAST:event_bttProdutoActionPerformed

    private void bttSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSairActionPerformed
        int escolha = JOptionPane.showConfirmDialog(this, "Sair");
        if(escolha==0){
            System.exit(0);
        }
    }//GEN-LAST:event_bttSairActionPerformed

    private void bttVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVendaActionPerformed
        if(this.venda==null || !this.venda.isDisplayable()){
            venda = new TelaVenda();
            desktop.add(venda);
            venda.setVisible(true);
            this.openInCenter(venda);
        }
        venda.toFront();
    }//GEN-LAST:event_bttVendaActionPerformed

    private void bttRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRelatorioActionPerformed
        if(this.relatorio==null || !this.relatorio.isDisplayable()){
            relatorio = new TelaRelatorio();
            desktop.add(relatorio);
            relatorio.setVisible(true);
            this.openInCenter(relatorio);
        }
        relatorio.toFront();
    }//GEN-LAST:event_bttRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCliente;
    private javax.swing.JButton bttProduto;
    private javax.swing.JButton bttRelatorio;
    private javax.swing.JButton bttSair;
    private javax.swing.JButton bttVenda;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JLabel labelRelogio;
    private javax.swing.JToolBar toolBarMenu;
    // End of variables declaration//GEN-END:variables
}
