/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote.telas;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pacote.Mock.MockProduto;
import pacote.classes.Produto;
import pacote.servico.ServicoProduto;
import pacote.validador.ValidadorProduto;

/**
 *
 * @author everton.aaraujo
 */
public class TelaProdutos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaProdutos
     */
    public TelaProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        abaCadastroProduto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDescricaoCadastrarProdutos = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        txtMarca = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        bttSalvarCadastroProduto = new javax.swing.JButton();
        bttCancelarCadastroProduto = new javax.swing.JButton();
        abaPesquisaProduto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDescricaoPesquisarProdutos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        bttPesquisar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Produto");

        abaCadastroProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Descrição");

        jLabel3.setText("Categoria");

        jLabel4.setText("Marca");

        jLabel5.setText("Modelo");

        jLabel6.setText("Cor");

        jLabel7.setText("Quantidade");

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher", "Cordas", "Percurssão", "Áudio", "Sopro", "Piano Teclado", "Amplificador", "Acessórios" }));

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        bttSalvarCadastroProduto.setText("Salvar");
        bttSalvarCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSalvarCadastroProdutoActionPerformed(evt);
            }
        });

        bttCancelarCadastroProduto.setText("Cancelar");
        bttCancelarCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCancelarCadastroProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaCadastroProdutoLayout = new javax.swing.GroupLayout(abaCadastroProduto);
        abaCadastroProduto.setLayout(abaCadastroProdutoLayout);
        abaCadastroProdutoLayout.setHorizontalGroup(
            abaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastroProdutoLayout.createSequentialGroup()
                        .addGroup(abaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(abaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantidade)
                            .addComponent(txtDescricaoCadastrarProdutos)
                            .addComponent(jComboBoxCategoria, 0, 461, Short.MAX_VALUE)
                            .addComponent(txtMarca)
                            .addComponent(txtModelo)
                            .addComponent(txtCor)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaCadastroProdutoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bttCancelarCadastroProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttSalvarCadastroProduto)))
                .addContainerGap())
        );
        abaCadastroProdutoLayout.setVerticalGroup(
            abaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescricaoCadastrarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttSalvarCadastroProduto)
                    .addComponent(bttCancelarCadastroProduto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar", abaCadastroProduto);

        abaPesquisaProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Pesquisar");

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Decrição", "Categoria", "Marca", "Cor", "Modelo", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(tabelaProduto);

        bttPesquisar.setText("Pesquisar");
        bttPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPesquisarActionPerformed(evt);
            }
        });

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaPesquisaProdutoLayout = new javax.swing.GroupLayout(abaPesquisaProduto);
        abaPesquisaProduto.setLayout(abaPesquisaProdutoLayout);
        abaPesquisaProdutoLayout.setHorizontalGroup(
            abaPesquisaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaPesquisaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addGroup(abaPesquisaProdutoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricaoPesquisarProdutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaPesquisaProdutoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        abaPesquisaProdutoLayout.setVerticalGroup(
            abaPesquisaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPesquisaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaPesquisaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDescricaoPesquisarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(abaPesquisaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pesquisar", abaPesquisaProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void bttCancelarCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCancelarCadastroProdutoActionPerformed
        int escolha = JOptionPane.showConfirmDialog(this, "Cancelar");
        if(escolha==0){            
            doDefaultCloseAction();
        }
    }//GEN-LAST:event_bttCancelarCadastroProdutoActionPerformed

    private void bttSalvarCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSalvarCadastroProdutoActionPerformed
        Produto produto = new Produto();
        produto.setDesc(txtDescricaoCadastrarProdutos.getText());
        String categoria = (String) jComboBoxCategoria.getSelectedItem();
        produto.setMarca(txtMarca.getText());
        produto.setModelo(txtModelo.getText());
        produto.setCor(txtCor.getText());
        produto.setQtde(txtQuantidade.getText());
        produto.setCat(categoria);
        ServicoProduto.cadastrarProduto(produto);
        
        if(ValidadorProduto.validador(produto)==0){
            txtDescricaoCadastrarProdutos.setText("");
            jComboBoxCategoria.setSelectedIndex(0);
            txtMarca.setText("");
            txtModelo.setText("");
            txtCor.setText("");
            txtQuantidade.setText("");
            
        }
        
        
        
    }//GEN-LAST:event_bttSalvarCadastroProdutoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bttPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPesquisarActionPerformed
        boolean resultSearch = false;
        ultimaPesquisa = txtDescricaoPesquisarProdutos.getText();
        
        try{
            resultSearch = refreshList();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Falha ao obter lista");
            return;
        }
        
        if(!resultSearch){
            JOptionPane.showMessageDialog(null, "Sem resultados");
        }
        
    }//GEN-LAST:event_bttPesquisarActionPerformed
            
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(tabelaProduto.getSelectedRow() >= 0){
            final int row = tabelaProduto.getSelectedRow();
            String desc = (String) tabelaProduto.getValueAt(row, 0);
            int resposta = JOptionPane.showConfirmDialog(null, "Excluir Produto\n"+desc+"?");
            if(resposta==0){
                try{
                    this.refreshList();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Falha na exclusão");
                }
            }
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    String ultimaPesquisa = null;
    
    public boolean refreshList(){
        List<Produto> resultado = ServicoProduto.procurarProduto(ultimaPesquisa);
        
        DefaultTableModel model = (DefaultTableModel) tabelaProduto.getModel();
        model.setRowCount(0);
        
        if(resultado==null || resultado.size() <=0){
            return false;
        }
        
        for(int i = 0; i < resultado.size(); i++){
            Produto produto = resultado.get(i);
            if(produto!=null){
                Object[] row = new Object[6];
                row[0] = produto.getDesc();
                row[1] = produto.getCat();
                row[2] = produto.getMarca();
                row[3] = produto.getModelo();
                row[4] = produto.getCor();
                row[5] = produto.getQtde();
                model.addRow(row);
            }
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaCadastroProduto;
    private javax.swing.JPanel abaPesquisaProduto;
    private javax.swing.JButton bttCancelarCadastroProduto;
    private javax.swing.JButton bttPesquisar;
    private javax.swing.JButton bttSalvarCadastroProduto;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtDescricaoCadastrarProdutos;
    private javax.swing.JTextField txtDescricaoPesquisarProdutos;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
